[tool.poetry]
name = "slashml"
version = "0.1.4"
description = "A Python client for interacting with SlashML services"
authors = ["eff-kay"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/slashml/slashml-python-client"
