apply_library_patches: true
base_image: null
build:
  arguments: {}
  model_server: TrussServer
bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
hf_cache: null
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: huggingface_transformer
model_metadata:
  has_hybrid_args: false
  has_named_args: false
  transformer_config:
    model: bert-base-uncased
model_module_dir: model
model_name: null
model_type: fill-mask
python_version: py39
requirements:
- transformers==4.30.0
- torch==2.0.1
- requests
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
runtime:
  predict_concurrency: 1
secrets: {}
spec_version: '2.0'
system_packages: []
train:
  resources:
    accelerator: null
    cpu: '1'
    memory: 2Gi
    use_gpu: false
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables: {}
